language: node_js

node_js:
  - "8"
  - "10"
  - "11"
  - "12"

os:
  - linux
  - osx

cache:
  directories:
    - "~/.npm"

jobs:
  include:
    - stage: danger
      node_js: "10"
      script: npx danger ci
      if: type = pull_request
